version: '3.7'

services:
  front:
    build:
      context: ./
      dockerfile: dev-front-Dockerfile
    tty: true
    environment:
      - NODE_ENV=local
    volumes:
      - ./front/:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - backend

  backend:
    build:
      context: ./
      dockerfile: dev-backend-Dockerfile
    tty: true
    environment:
      - NODE_ENV=local
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 3100:3100
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=portfolio
    ports:
      - 5432:5432
    volumes:
      - "./dbdata:/var/lib/postgresql/data"

  redis:
    image: redis:5
    ports:
      - "6379:6379"
